/*
-----------------------------------------------------------------------------
Names           Talah Al-Zamel, Ethan Sigfusson, Kim Carino
Course name     COMP 2659-002
File name       EFFECTS.H
Professor       Steve Kalmar
-----------------------------------------------------------------------------
*/

#ifndef EFFECTS_H
#define EFFECTS_H

void initPsg();
void playJumpSound();
void playDeathSound();

#endif
