splashtst: splashtst.o splash.o raster.o objects.o
	cc68x -g splashtst.o splash.o -o tstsplash

splashtst.o: splashtst.c splash.h raster.h objects.h
	cc68x -g -c splashtst.c

splash.o: splash.c splash.h input.h
	cc68x -g -c splash.c

raster.o: raster.c raster.h
	cc68x -g -c -I..\stage-2 raster.c

