splashtst: splsh.o splash.o raster.o objects.o font.o input.o
	cc68x -g splsh.o splash.o raster.o objects.o font.o input.o -o splashtst

splsh.o: splsh.c
	cc68x -g -c splsh.c

splash.o: splash.c
	cc68x -g -c splash.c
