/*
-----------------------------------------------------------------------------
Names           Talah Al-Zamel, Ethan Sigfusson, Kim Carino
Course name     COMP 2659-002
Stage           Stage 7
Deadline        March 17, 2024
File name       EFFECTS.H
Professor       Steve Kalmar
-----------------------------------------------------------------------------
*/

#ifndef EFFECTS_H
#define EFFECTS_H

void playJumpSound();
void playDeathSound();

#endif
