tst_psg: tst_psg.o psg.o music.o effects.o clock.o
	cc68x -g tst_psg.o psg.o music.o effects.o clock.o -o tst_psg 

tst_psg.o: tst_psg.c psg.h
	cc68x -g -c -I..\stage-5 tst_psg.c

psg.o: psg.c psg.h
	cc68x -g -c psg.c
music.o: music.c  music.h
	cc68x -g -c -I..\stage-5 music.c
effects.o: effects.c effects.h
	cc68x -g -c effects.c

