/*
Names 			Talah Al-Zamel, Ethan Sigfusson, Kim Carino
Course name   	COMP 2659-002
Stage	    	Stage 2
File name       CONST9.H
Professor     	Steve Kalmar

Purpose:
stores stage 9 constants
*/

#ifndef CONST9_H
#define CONST9_H

typedef void (*Vector)();


#define VblVect 28
#define IKBDVect 70

/*inputs are defined as their makecodes*/

#define escKey 0x01
#define oneKey 0x02
#define twoKey 0x03

#define wKey= 0x11
#define sKey = 0x1f


#endif